FROM node AS node-build

COPY ClientApp /app

WORKDIR /app

RUN npm install

RUN npm run build

FROM mcr.microsoft.com/dotnet/sdk:6.0 as dotnet-build

RUN apt-get update && \
  apt-get --no-install-recommends -y install nodejs npm

COPY ./ /app
COPY --from=node-build /app /app/ClientApp

WORKDIR /app

RUN dotnet publish -c release -o publish -r linux-x64 Requestrr.WebApi.csproj

FROM mcr.microsoft.com/dotnet/aspnet:6.0

COPY --from=dotnet-build /app/publish/ /root/

# allow all users access to this so we can run container as non root.
# create /root/tmp if nonexistent
RUN chmod -R 755 /root && mkdir /root/tmp && chmod -R 777 /root/tmp

WORKDIR /root/

ENV ASPNETCORE_URLS="http://*:4545"
EXPOSE 4545/tcp
ENTRYPOINT ["dotnet", "Requestrr.WebApi.dll"]
